<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Compositor</RootNamespace>
    <AssemblyName>Compositor</AssemblyName>
    <ApplicationTitle>Compositor</ApplicationTitle>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Compositor.Core\Compositor.Core.csproj" />
  </ItemGroup>
</Project>
